variable "public_key" {}
variable "private_key_path" {}
variable "key_name" {}
variable "aws_region" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "aws_amis" {}
variable "sg_id" {}
variable "vpc_name" {}
variable "vpc_prefix" {}
variable "project" {}
variable "service_name" {}
variable "aws_instance_type" {}
variable "ami_id" {}
variable "run_list" {}
